apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: orbitstack-secrets
  namespace: orbitstack
  labels:
    app.kubernetes.io/name: orbitstack-secrets
    app.kubernetes.io/part-of: orbitstack-platform
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB+dummy+encrypted+data+for+POSTGRES_PASSWORD=
    SECRET_KEY: AgB+dummy+encrypted+data+for+SECRET_KEY=
    DATABASE_URL_AUTH: AgB+dummy+encrypted+data+for+DATABASE_URL_AUTH=
    DATABASE_URL_CATALOG: AgB+dummy+encrypted+data+for+DATABASE_URL_CATALOG=
    DATABASE_URL_ORDER: AgB+dummy+encrypted+data+for+DATABASE_URL_ORDER=
  template:
    metadata:
      name: orbitstack-secrets
      namespace: orbitstack
    type: Opaque
